language: go
services:
- docker
go:
- 1.7
env:
  global:
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - secure: wVUxvqGFIbrNKwwAPybnaOFUqqZ/5pikMCK385DMkQ8Iw9o5unEqOUH1sHOXLbzfiB7JjlRO0IYMWinyk7p6avHH4DP4lLQnw9HwIaqxMsmZ+D8s6DthCIvjpLRwcWabU4Nw3yxq871BHd99sF+VsPOFIVYAZJYbYddzosKgoRIVTK6J1Pi0pNdiSyW7dqIGTj/ne5MZsVriNGqV9BPaosjFo7U/d9xoIwuRuqlgMAx7tERvyOO5lBQOKFr4LmDxdWTl/coYWqMSeaFQOPIK7yWmUdmFXkzYzKTu4z5kuqcafD38DkTHR02wCopGe2LUo1/UyEhn0TETWffEYjgmbbijEBsRlea/qOH4Ucc8IfQksZMUBYeQXsFzGjwGOgBIRpGbz3UEGSgnMeo/E9PAbVk2R0LANQWk0PpgJVg8/c0BHKTxnBwrNF5s8K4Unsq3Gg6gfu/XSxfoOUU8f24iKqIIhThboYHu0s8/r/gmMeqDhf4VeYBsi8LpNmCja2gcrPhk7pJ30mpjMjgaMomC4maGnULWqZfSZlj9WPXftKG61cgRljnwSoVWjQPwVsPgsI8+9jwAsHWDjCKlt63RWUubO45Ji8/H2kXpe+wTTYkqp29h0PEMCOTZaJ6P6HrmtWK/S5TIhirIpdktcmqrh2xtfKgDoAU8mMLi9+iUVx4=
  - secure: FayJhyI6W3RIjeHa27mMCuw4ldAqL6m5eUGTak14DwU5OeECTsVdOWR3zI/tLrZLIB7WvWbPHG77gkbeYKChHCYZ7IbFvjQzDCnOnRu2tcL++Jwhj5bSq0wD9D6U0nEtPQLWVtF9MOGCPtG1hrPrhjLuDXFUXvJD4NhXTfipU/ULcbQ1mh4rLo+eHtcE5M+cZp11pMxReSSsC+cziFJGleP2Ikh8HwdtBHX4fEXYoBHOz4g9/w9kFz7/TJUS+zhGrczMUpMTBj+eMgYc7zY5fEQ+irjzzcttR8ixxLstOrl2ikgikRjMfv7YomXCsrEUipbNzvlCCKlfeBNAi7huZt8z8fvqDjdaK4sHncxSK7v9Vg5x01428MnPwio+mREaoao4U7ClhdRNyMTFQzlfcZMAFi/14OtrWP89cxEi9ATpnSnv2vjwnWO166D54Ll70KxwN3aBJSxuXQP0ENhYLc8J5K9/rFl9iD3NK12eHVieL33/sMqKYcBoxlRoxbu21iGvHK/TRP7keHVU1cZhdIDddp5CowVbdriOtDnFRJBAcDfyMz4d9LDemKhg/fngwM208R44BcD5/Vu6Kqfc8Eg9A4f9V8xzZcmkPWCqxsffY1pvuDG9t7cNWkG2IVmzXlxDe/poHkOKO8L02VSiuyg1z3i9diQ+KhSguV9xLmg=
  - secure: oj8zXrWW61nit5tWeRXgxwlm3kxkAOi9gwNnYxIG3MgiN05vpNrBt0Bq9/yaqlvxoUMZd+USSk+NMENk36v2nVN7z2Z0Setcah3zzOC54JsOUzFYtdJona2HYSfEKLNz9yWqgFt1Ih/EfcZGpdT0gFwHDodO5okFcoRzYCM6Gl0vQ6TKMcF+fBmD5PTDx+1gyr9kaDpewWQFM/SuokW0xsWdgKBPPYjN31cdFEJ2phEoSRYvQfXe3bO5DDmJNIGAw/wLdbv0qKZussCz13DFEhDwTQBB2aDPx/fH9V8+o4T4mN4fNuXYjHDadf9urwcQBscwdxVQdYomFkrG0f8dJIL8N+4eq5/tGTLqNtu9vaM52FuXAcAxhIrlX7dVDqrjqKrS6z4had8SxpAU3sqjS9nOJny/OwiGohhPbMSORDV9xYoYfK7yGCdeWTfsSI7nciHfp2NJqmVXYRA5X1HPXZS9K9Ln8+y6fRHCWgaIv7S3wlJwVGfqzFHUsEGGEbo4Fs3/fLfPweMggMPqWWljWEdrBZtGBseDeWLTK0qbGCXs7aDNxNGHSXR1PdZ+cW3GMKKAygr+B4VsZfAWUP8Vyl2QW6PR93VHRpC8jc2BrYrWDSHJDqATImSIy7MpgHLUyfVPN3WzEOWX+Xpp16fhjKMp0gWIPBMUOBxhbF5FW1s=
branches:
  only:
  - master
  - "/^\\d+\\.\\d+\\.\\d+/"
script:
- go vet
- go test github.com/nytimes/drone-gdm/plugin
- go build -ldflags "-s -w -X main.lbl=$TRAVIS_BRANCH -X main.build=$TRAVIS_BUILD_NUMBER
  -X main.rev=$TRAVIS_COMMIT" -a -tags netgo
after_success:
- if [ "$TRAVIS_BRANCH" == "master" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then docker
  build -t "nytimes/drone-gdm:latest" . ; docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME"
  -p="$DOCKER_PASSWORD" ; docker push "nytimes/drone-gdm:latest"; fi
- if [ "x$TRAVIS_TAG" != "x" -a "$TRAVIS_PULL_REQUEST" == "false" ]; then docker build
  -t "nytimes/drone-gdm:$TRAVIS_TAG" . ; docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME"
  -p="$DOCKER_PASSWORD" ; docker push "nytimes/drone-gdm:$TRAVIS_TAG"; fi
