language: go
go_import_path: github.com/nytimes/drone-gdm
services:
- docker
go:
- 1.15
env:
  global:
  - CGO_ENABLED=0
  - GOOS=linux
  - GOARCH=amd64
  - secure: 0N6HNlO2bAAO/x2u8u3wFykIElbVuZ8VIzFfGoshTq+tOpEpVs0eXhIy92jJUCEOCnfUNwLppn6HYURqFsB6lKA2ZkVE5JVVFdtxw5J6MIHrEbLH7H/TakrifaqaCdms/68SBPwVKa2D0Mgsy1Rdz1E/C4/VPn9uJUH1ESdZWCCSRt1NNvB/s3a8UYXWEJjullRZ1YPrmqBOrvjkz3YBJ0qqatQyusERT5QQ8GLkoKhot8B7t7tzbv3/eaQNfPQMNxFAY2hufavVJ/DV8+8JG6OkK2TN3O0SinV40um3EEv1kwCyVmHG2Js5YBzD7RlmsTzlMnbPhyXvXHImwOl04vZqBttVTNOqzAK6OYb1qku3Obvphqky5BYM2wFLVr0IYx80eFaqP/Iq5ersNQUISA5ys3spKVn36JmtneCe6u4TMFvUZBpwdf+e7gJozRobmr4pYIdej8J8v5fptwxyKeD3QbY6iM0AvznTAFdbtRAA1jkt2qQqhYLN4aeaTBnAhO56vNcPFep/z4NyWvI7IJcx1Mn/Z5DkynbAx+oIRT6tzJ9KG//E1D6pb8mO1n3IucrZgd3zwAt+nGYBoOsMVVAuZr1wqSr+gnVxm81+DcYUZZ5cNbq+qb/A/bKvqAXoCiy00qFX3IXDiw38hRXmJkUwL3LXeBrhgG3Ts584zn4=
  - secure: IDdoMl8dxVo6UCCZ1k4lAIVEBIp+WzkntU+N9iv2i7duZF/GnH2Jt5WgSa5i/NOvC4To4FeEaB0WHNu4NHQ9C2+oDJvVuXKPC8OVT7UjI8VviJdmGisiDUFoBPiGwhvCBnkmpRimnzUThut7WbTny7HT7FFm6H+bQQ1qmKVIM0oc+3eHIczKE0DM1L20Lk4S5VSrbBF3jWsfWv4M3CbrYwzJ24fyImn5VWi0CLfQBa8MaaJI9uaGhUIIyRHZE4nXPUnfjb8yxZEO6c3VY0GAjXIn5gI4uQSuEn2y+NlGvvgJjO5zky3o00zBH9/31reafoxgi9upVvnNazXfjS4FLVcIl1QDKDxx705XYWRAU91jRwWQYPIiyKDpPtFi7MqbbJQdoqVSCafBEDFFcSitWV0itUW1HeRYeolUi2YGJ2Ed4kNmxRGW3w0IOcrtGMnIQh2/QCkz4PNZO5QcF/2qXGt0rheqiRuVHRQrFyCS+iilUBxfpKmDXqa/TegBQYUP3u+CTf4NjqQY19SgS8LHHAmD3wC+c90aZYfMoEJOK/mDLtIeBM2uFPLXPDBF6B5EFa96SouUHBkhGJ25/d9bwthPVQLlt8N512JgwSjNBNZdG10TgNDgwsY7EZGTH1d5Z3ncaeMQZjWmLUiJJc1X312R748VyruCsMYCPGSF0mg=
branches:
  only:
  - main
  - develop
  - /^\d+\.\d+\.\d+[ab]*/
script: ./travis/script.sh
after_success: ./travis/after-success.sh
